name: ci
on:
  push:
    branches:
      - master
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Set Cache ID
        run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 

      - uses: actions/cache@v4
        with:
          path: .cache
          key: mkdocs-material-${{ env.cache_id }}
          restore-keys: mkdocs-material-

      - name: Install Dependencies
        run: |
          pip install mkdocs-material
          pip install mkdocs-link-preview-plugin
          pip install beautifulsoup4

      - name: Deploy to GitHub Pages
        if: github.repository == 'tankala/learn-pip-trends'
        run: mkdocs gh-deploy --force
